title: movity - GitHub
email: mandi@movity.it
description: This website contains list of all the open source repositories on github by movity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://movityit.github.io" # the base hostname & protocol for your site, e.g. http://example.com
about_url: https://movity.it
twitter_username: movityit
github_username: movityit
author: movity
lang: it-IT
google_analytics: 

timezone: Europe/Rome

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
#  - jekyll-mentions
#  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - screenshot.png
